# This file is automatically generated by EBNFParser.
from Ruikowa.ObjectRegex.Tokenizer import unique_literal_cache_pool, regex_matcher, char_matcher, str_matcher, Tokenizer
from Ruikowa.ObjectRegex.Node import AstParser, Ref, SeqParser, LiteralValueParser as L, LiteralNameParser, Undef
namespace = globals()
recur_searcher = set()
token_table = ((unique_literal_cache_pool["auto_const"], str_matcher(('just'))),)

class UNameEnum:
# names

    Just = unique_literal_cache_pool['Just']
        
cast_map = {}
token_func = lambda _: Tokenizer.from_raw_strings(_, token_table, ({}, {}),cast_map=cast_map)

Just = AstParser([SeqParser(['just'], at_least=1,at_most=Undef)],
                 name="Just",
                 to_ignore=({}, {}))
Just.compile(namespace, recur_searcher)