from Misakawa.ErrorFamily import handle_error
from parser import *
import argparse

cmdparser = argparse.ArgumentParser(description='Test Parser Generated by EBNFParser.')
cmdparser.add_argument("Parser", type = str,
                       help='What kind of parser do you want to test with?(e.g Stmt, Expr, ...)')
cmdparser.add_argument("Codes",  metavar = 'lispCodes', type = str,
                       help='Input some codes in your language here.')

args = cmdparser.parse_args()

parser = handle_error(eval(args.Parser).match)

tokenized = token.findall(args.Codes)

print(parser(tokenized))





