#
__VERSION__ = "0.2.0"
__AUTHOR__  = 'thautwarm'
__doc___="""
   what's new in EBNFParser 0.1.2:
	1.
		separate parser with tokenizer.
		You are allowed to whether to define tokenizer automatically in EBNF files.
		You are allowed to define a funtion to be the tokenizer at the first line in a EBNF file
		for instance:
			using {{ lambda string:list(string) }} # or just list

		And you are allowed to write a tokenizer definition in another file, for instance:

		file: ./xxx.eebnf
			using python.token
		file: ./python/token
			lambda x : string(x)
		Take care that you can just write an expression!!!
	2.
		the meta information format has changed from

			"meta":{"rowIdx":<rowIdx>, "count":<count>, "fileName":<fileName>}
		to
			"meta":[<rowIdx>, <count>, <fileName>]

	Enjoy it:)


   what's new in EBNFParser 0.1.2.2:
	
	You're now allowed to define parsers named by chinese characters. 


   what's new in EBNFParser 0.1.3.1:
	
	There is a module named `token` which is in CPython STL.
	As a result, I changed the name of a specific file generated by Parser Generator from `token.py` to `etoken.py`.
 
   what's new in EBNFParser 0.1.3.4(0.1.4):
	
	Fixed bugs for Windows users.
	Now just use following command 

	```
	parserGenerator <grammarFile> <outputParser.py> 
		-lang <yourLanguageName> 
		-comment <hasComments?>
		-multiline <hasMultilineDefinitions?>
	```
	to generate a parser.

   what's new in EBNFParser 0.2.0:
	
	I think that I have just found a fantastic method to solve left recursion problem.
	The way to do it is just:

		- mark the left-recursive parser node and store the tail of each epsilon production of this parser as TAIL.
		```
		a ::= a b c | a '=>' d | c
		# TAIL = b c | '=>' d 
		```
		- when an ast named RESULT has been parsed, just

			* make an new ast also named RESULT', take RESULT as the first elem in RESULT'!!!
			* continue parsing by using TAIL.
	
	I will refactor this method sooner to make my codes more elegant.

	- P.S
		Sometimes I think my ideas might come from God's Revelation.
		It seems so incredible for me to totally solve a part of Principles by myself.

""" 
